name: 'publish-pytest-action'
description: 'Publishing pytest result Github Action to comment on PR'
author: 'sambyeol'

branding:
  icon: 'zap'
  color: 'blue'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
