name: 'publish-pytest-action'
description: 'Publishing pytest result Github Action to comment on PR'
author: 'sambyeol'

branding:
  icon: 'zap'
  color: 'blue'

inputs:
  junitxml:
    description: 'path to junitxml file'
    required: true

  coverage_xml:
    description: 'path to coverage xml file'
    required: true

outputs:
  failed:
    description: 'failed test count'

  coverage:
    description: 'coverage percentage'

runs:
  using: node20
  main: dist/index.js
