name: 'publish-pytest-action'
description: 'Publishing pytest result Github Action to comment on PR'
author: 'sambyeol'

branding:
  icon: 'zap'
  color: 'blue'

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

  title:
    description: 'title of the comment'
    default: 'Pytest Report'
    required: false

  junit-xml:
    description: 'path to junit xml file'
    required: true

  coverage-xml:
    description: 'path to coverage xml file'
    required: false

  comment-identifier:
    description:
      'A unique identifier for the comment, typically derived from matrix
      variables (e.g., `py${{ matrix.python-version }}-${{ matrix.os }}`). Used
      to ensure `comment-mode` (`update`, `hide`, `delete`) targets only
      comments from the same job or matrix configuration.'
    required: false
    default: ''

  comment-mode:
    description: |
      How to handle previous comments from this action.
      - `update`: Update the previous comment.
      - `hide`: Hide previous comments.
      - `delete`: Delete previous comments.
      - `new`: Create a new comment.
    required: false
    default: 'new'

outputs:
  failed:
    description: 'failed test count'

  coverage:
    description: 'coverage percentage'

runs:
  using: node20
  main: dist/index.js
