name: 'publish-pytest-action'
description: 'Publishing pytest result Github Action to comment on PR'
author: 'sambyeol'

branding:
  icon: 'zap'
  color: 'blue'

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

  junit-xml:
    description: 'path to junit xml file'
    required: true

  coverage-xml:
    description: 'path to coverage xml file'
    required: false

outputs:
  failed:
    description: 'failed test count'

  coverage:
    description: 'coverage percentage'

runs:
  using: node20
  main: dist/index.js
